import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import dotenv from 'dotenv'
import './globals.css'
import '@/assets/iconfont/iconfont.css'

const inter = Inter({ subsets: ['latin'] })

dotenv.config()

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
